"""CLI: manufacture the raw feed pile a custodian would have sent us.

For each business day in the range, emits one delivery into
`<out>/date=YYYY-MM-DD/`:

- `ACC-GROWTH-001.semt002.xml`  (holdings, ISO 20022)
- `ACC-GROWTH-001.mt535.txt`    (holdings, SWIFT MT)
- `ACC-GROWTH-001.camt053.xml`  (cash, ISO 20022)

Hive-style `date=` directories so Spark can partition-prune later.

Corruption policy (D-011): the two holdings renditions are corrupted
*independently* (different seeds) — so the semt.002 and MT535 views of
the same day genuinely disagree sometimes, which is what cross-feed
reconciliation exists to catch. Everything derives deterministically
from the date, so any historical day can be regenerated byte-identically.

Ground truth (what was injected, per file, with checksums) is written to
`<out>/../manifests/YYYY-MM-DD.json` — deliberately OUTSIDE the raw
landing directory: the pipeline must never read it; only Phase 3's
detection-quality evaluation may.
"""

import argparse
import hashlib
import json
from datetime import date, timedelta
from pathlib import Path
from random import Random

from parvum_ingest.book import build_book, build_cash_statement
from parvum_ingest.defects import DefectConfig, DefectType, inject_cash, inject_holdings
from parvum_ingest.formats.camt053 import render_camt053
from parvum_ingest.formats.mt535 import render_mt535
from parvum_ingest.formats.semt002 import render_semt002

_HOLDINGS_POOL = (
    DefectType.MISSING_COST_BASIS,
    DefectType.MISTYPED_ISIN,
    DefectType.STALE_PRICE,
)
_CASH_POOL = (
    DefectType.DUPLICATE_TRANSACTION,
    DefectType.DROPPED_TRANSACTION,
    DefectType.SETTLEMENT_SHIFT,
)
# Per day and defect type, the chance it's present in that day's delivery.
_DEFECT_PROBABILITY = 0.25


def _day_seed(day: date, salt: int) -> int:
    # Derived from the calendar date so a given day is always regenerable;
    # salted so each stream (semt/mt/cash) corrupts independently.
    return int(day.strftime("%Y%m%d")) * 10 + salt


def _pick_defects(pool: tuple[DefectType, ...], rng: Random) -> tuple[DefectType, ...]:
    return tuple(d for d in pool if rng.random() < _DEFECT_PROBABILITY)


def _sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def generate_day(day: date, out_dir: Path) -> dict:
    """Write one day's delivery; return its manifest entry."""
    account_id = build_book(day).account.account_id
    day_dir = out_dir / f"date={day.isoformat()}"
    day_dir.mkdir(parents=True, exist_ok=True)

    streams = []

    def _emit(filename: str, fmt: str, text: str, injections: list) -> None:
        (day_dir / filename).write_text(text, encoding="utf-8", newline="\n")
        streams.append(
            {
                "name": filename,
                "format": fmt,
                "bytes": len(text.encode("utf-8")),
                "sha256": _sha256(text),
                "injections": [r.model_dump(mode="json") for r in injections],
            }
        )

    book = build_book(day)
    cash = build_cash_statement(day)

    semt_cfg = DefectConfig(
        seed=_day_seed(day, 1), defects=_pick_defects(_HOLDINGS_POOL, Random(_day_seed(day, 1)))
    )
    semt_book, semt_inj = inject_holdings(book, semt_cfg)
    _emit(f"{account_id}.semt002.xml", "semt.002", render_semt002(semt_book), semt_inj)

    mt_cfg = DefectConfig(
        seed=_day_seed(day, 2), defects=_pick_defects(_HOLDINGS_POOL, Random(_day_seed(day, 2)))
    )
    mt_book, mt_inj = inject_holdings(book, mt_cfg)
    _emit(f"{account_id}.mt535.txt", "MT535", render_mt535(mt_book), mt_inj)

    cash_cfg = DefectConfig(
        seed=_day_seed(day, 3), defects=_pick_defects(_CASH_POOL, Random(_day_seed(day, 3)))
    )
    cash_stmt, cash_inj = inject_cash(cash, cash_cfg)
    _emit(f"{account_id}.camt053.xml", "camt.053", render_camt053(cash_stmt), cash_inj)

    return {"date": day.isoformat(), "account": account_id, "files": streams}


def generate(end: date, days: int, out_dir: Path) -> list[dict]:
    """Generate deliveries for the `days` calendar days ending at `end`,
    skipping weekends (custodians send on business days). Returns the
    manifests, which are also written to <out>/../manifests/."""
    manifest_dir = out_dir.parent / "manifests"
    manifest_dir.mkdir(parents=True, exist_ok=True)

    manifests = []
    for offset in range(days - 1, -1, -1):
        day = end - timedelta(days=offset)
        if day.weekday() >= 5:  # 5=Sat, 6=Sun
            continue
        manifest = generate_day(day, out_dir)
        (manifest_dir / f"{day.isoformat()}.json").write_text(
            json.dumps(manifest, indent=2), encoding="utf-8", newline="\n"
        )
        manifests.append(manifest)
    return manifests


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate synthetic custodial feed files.")
    parser.add_argument("--end", type=date.fromisoformat, default=date.today(), help="last day")
    parser.add_argument("--days", type=int, default=90, help="calendar days back from --end")
    parser.add_argument("--out", type=Path, default=Path("../data/raw"), help="landing directory")
    args = parser.parse_args()

    manifests = generate(args.end, args.days, args.out)
    total_files = sum(len(m["files"]) for m in manifests)
    print(f"{len(manifests)} business days -> {total_files} files under {args.out}")


if __name__ == "__main__":
    main()
